---
name: MusicServer
version: 1.0.4
slug: musicserver
description: Snapcast, Librespot and Shairport for Home Assistant
arch:
- amd64
startup: services
init: false
boot: auto
host_network: true
webui: http://[HOST]:[PORT:1780]/