---
name: MusicServer2
version: 1.0.26
slug: musicserver2
description: Snapcast, Librespot and Shairport for Home Assistant
arch:
  - amd64
startup: services
init: false
boot: auto
host_network: true
ports:
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
  4953/tcp: 4953
webui: http://[HOST]:[PORT:1780]/
