---
name: MusicServer
version: 1.0.2
slug: musicserver
description: Snapcast, Librespot and Shairport for Home Assistant
arch:
- amd64
startup: services
init: false
boot: auto
ports:
  1780/tcp: 1780
